# Generated by Django 4.1.1 on 2022-09-23 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='description',
            field=models.TextField(max_length=1500, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='completion_data',
            field=models.TextField(default=None, null=True, verbose_name='Date of completion'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('process', 'Process'), ('made', 'Made')], default='New', max_length=50, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='text',
            field=models.CharField(max_length=500, verbose_name='Text'),
        ),
    ]
