# Generated by Django 4.1.1 on 2022-09-30 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_todo_description_alter_todo_completion_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='deleted_at',
            field=models.DateTimeField(default=None, null=True, verbose_name='Date of delete'),
        ),
        migrations.AddField(
            model_name='todo',
            name='is_delete',
            field=models.BooleanField(default=False, verbose_name='Delete'),
        ),
    ]
